import type { Metadata } from "next";
import { Inter, Space_Grotesk, Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/sidebar";
import Providers from "./providers";
import { ThemeProvider } from "@/components/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { ModeToggle } from "@/components/theme-toggle";
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

export const metadata: Metadata = {
  title: "Website Builder",
  description: "Generated by create next app",
};
const originalError = console.error;
console.error = (...args: unknown[]) => {
  if (typeof args[0] === "string" && args[0].includes("script tag")) return;
  originalError(...args);
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(roboto.variable, geistMono.variable)}>
        <Analytics />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <SidebarProvider>
              <main className="w-full">
                <SessionProvider>
                  <NextTopLoader color="white" showSpinner={false} />
                  {children}
                  <ModeToggle />

                  <Toaster richColors position="bottom-right" />
                </SessionProvider>
              </main>
            </SidebarProvider>
          </Providers>
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
